import type { Metadata } from "next";
import { Header, Footer } from "@/components";
import { poppins, robotoSlab } from "@/assets/fonts";
import "@/assets/globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: {
  home: React.ReactNode;
  about: React.ReactNode;
  projects: React.ReactNode;
  contact: React.ReactNode;
}) {

  const cssFonts = `${poppins.variable} ${robotoSlab.variable}`;
  return (
    <html lang="en" className={cssFonts}>
      <body>
        <Header />
        <main>
          {props.home}
          {props.about}
          {props.projects}
          {props.contact}
        </main>
        <Footer />
      </body>
    </html>
  );
}
